crates/op-rbuilder/src/payload_builder_vanilla.rs

Change the reverting hashes from trace to info as it'll be an important source of transaction tracing.
---

Add info log for reverting tx hashes

---

.github/workflows/release.yaml

Removed op- prefix for tags, because we are in op-rbuilder repo now
Added runners for docker building to speed up arm64 
Put more robust repo name
---

feat: Improve github CI for docker building

---

.github/workflows/checks.yaml
Makefile
crates/op-rbuilder/src/generator.rs
crates/op-rbuilder/src/integration/mod.rs
crates/op-rbuilder/src/main.rs
crates/op-rbuilder/src/metrics.rs
crates/op-rbuilder/src/tester/main.rs
crates/op-rbuilder/src/tester/mod.rs

Use nightly for clippy and fmt

---

crates/op-rbuilder/src/monitor_tx_pool.rs

Bump monitoring log from debug to info

Bump monitoring log

---

crates/op-rbuilder/src/args.rs
crates/op-rbuilder/src/generator.rs
crates/op-rbuilder/src/integration/integration_test.rs
crates/op-rbuilder/src/integration/mod.rs
crates/op-rbuilder/src/integration/op_rbuilder.rs
crates/op-rbuilder/src/main.rs
crates/op-rbuilder/src/payload_builder.rs
crates/op-rbuilder/src/payload_builder_vanilla.rs

Enable revert protection behind a flag `--builder.enable-revert-protection`. This PR also adds an extra integration test to test the behaviour.

Add flag to enable revert protection

---

crates/op-rbuilder/src/integration/integration_test.rs
crates/op-rbuilder/src/integration/mod.rs
crates/op-rbuilder/src/integration/op_rbuilder.rs
crates/op-rbuilder/src/integration/op_reth.rs

This PR introduces an e2e test that check that the builder is emitting a log with the transaction monitor when a transaction is discarded.

Add e2e test to check that the builder emits a log when a transaction is discarded

---

Cargo.lock
Cargo.toml
crates/op-rbuilder/Cargo.toml
crates/op-rbuilder/src/integration/integration_test.rs
crates/op-rbuilder/src/integration/op_rbuilder.rs
crates/op-rbuilder/src/payload_builder_vanilla.rs
crates/op-rbuilder/src/tester/main.rs
crates/op-rbuilder/src/tester/mod.rs

This PR enables the Reth payload generator for the vanilla block builder and introduces a new integration test that validates that under short block times the blocks still include transactions.

Have the option to use the reth payload generator

---

Cargo.lock
Cargo.toml
Dockerfile
crates/op-rbuilder/Cargo.toml
crates/op-rbuilder/src/bin/tester/main.rs
crates/op-rbuilder/src/payload_builder.rs
crates/op-rbuilder/src/payload_builder_vanilla.rs
crates/op-rbuilder/src/tests/framework/apis.rs
crates/op-rbuilder/src/tests/framework/harness.rs
crates/op-rbuilder/src/tx_signer.rs
rust-toolchain.toml

This is PR dedicated only to reth 1.4.1
I will add integration tests in follow-up PRs 
---

Bump reth to 1.4.1

---

crates/op-rbuilder/src/bin/tester/main.rs
crates/op-rbuilder/src/tests/framework/blocks.rs
crates/op-rbuilder/src/tests/vanilla/revert.rs

This PR introduces a helper for the e2e tests to check whether a transaction was included in a block

Add helper utility to check for block inclusion in e2e tests

---

crates/op-rbuilder/src/primitives/bundle.rs
crates/op-rbuilder/src/revert_protection.rs
crates/op-rbuilder/src/tests/framework/txs.rs

To be compatible with the sendBundle type, the result should be an object with the bundle hash not only the hash. https://docs.flashbots.net/flashbots-auction/advanced/rpc-endpoint#eth_sendbundle
---

Fix bundle result

---

Cargo.lock
Cargo.toml
crates/op-rbuilder/Cargo.toml
crates/op-rbuilder/src/args/op.rs
crates/op-rbuilder/src/builders/context.rs
crates/op-rbuilder/src/builders/flashblocks/payload.rs
crates/op-rbuilder/src/builders/standard/payload.rs
crates/op-rbuilder/src/main.rs
crates/op-rbuilder/src/primitives/reth/execution.rs
crates/op-rbuilder/src/tests/framework/blocks.rs
crates/op-rbuilder/src/tests/framework/harness.rs
crates/op-rbuilder/src/tests/framework/op.rs
crates/op-rbuilder/src/tests/vanilla/data_availability.rs
crates/op-rbuilder/src/tests/vanilla/mod.rs
crates/op-rbuilder/src/tests/vanilla/revert.rs
crates/op-rbuilder/src/tests/vanilla/txpool.rs

Supersedes https://github.com/flashbots/op-rbuilder/pull/7 and https://github.com/flashbots/op-rbuilder/pull/8
Added some extra integration tests for txpool
---

Use correct DA transaction compression

---

crates/op-rbuilder/src/builders/standard/payload.rs

Adds back the total block building duration metric that was lost during refactor of vanilla builder.
resolves https://github.com/flashbots/op-rbuilder/issues/75
---

Add total_block_built_duration metric back to vanilla builder

---

crates/op-rbuilder/src/builders/context.rs
crates/op-rbuilder/src/tests/vanilla/data_availability.rs
crates/op-rbuilder/src/tx.rs

Used function that integrates downscaling
---

Fix da scaling issue

---

Cargo.toml
crates/op-rbuilder/src/args/mod.rs
crates/op-rbuilder/src/main.rs
crates/op-rbuilder/src/metrics.rs

Move VERSION to different crate
closes https://github.com/flashbots/op-rbuilder/issues/14
---

Add replacement for default reth version

---

README.md

Update features specified in docs.
Ensure the docs are consistent with the code
---

fix: update features flags

---

crates/op-rbuilder/Cargo.toml
crates/op-rbuilder/src/builders/context.rs

This PR adds feature-gated interop support. Right now to produce interop binary we'll need to make PR with this support.
Long term we will remove this feature once we are comfortable enabling interop for everyone.
Uses derive-more for display. 
---

Added feature-gated interop support

---

crates/op-rbuilder/src/builders/context.rs
crates/op-rbuilder/src/metrics.rs

Current summary metrics is misleading a bit so we will replace it with gauge
---

Use Gauge for da size limits

---

crates/op-rbuilder/src/builders/context.rs
crates/op-rbuilder/src/builders/flashblocks/payload.rs
crates/op-rbuilder/src/builders/standard/payload.rs

Closes https://github.com/flashbots/op-rbuilder/issues/90
---

Account for DA and gas limit in flashblocks

---

Cargo.lock
Cargo.toml
crates/op-rbuilder/Cargo.toml
crates/op-rbuilder/src/builders/context.rs
crates/op-rbuilder/src/builders/flashblocks/payload.rs
crates/op-rbuilder/src/builders/flashblocks/wspub.rs
crates/op-rbuilder/src/tests/framework/apis.rs
crates/op-rbuilder/src/tests/framework/blocks.rs
crates/op-rbuilder/src/tx.rs

upgrade reth to 1.4.7.
bug fixes and compatibility with the latest rollup-boost
---

Upgrade to reth 1.4.7 and main rollup-boost branch

---

crates/op-rbuilder/src/builders/flashblocks/payload.rs
crates/op-rbuilder/src/builders/flashblocks/wspub.rs

Adding block number to building logs allows to debug things more easily, also adding da used. 
---

Add block number and DA used to logging

---

README.md
justfile

This PR adds a just command for running tests, which automatically downloads op-reth using the CI script and adds it to the PATH.
There's no need to manually modify the PATH to add an `op-reth` binary.
---

feat: add a justfile to run tests

---

crates/op-rbuilder/src/revert_protection.rs

If a user only specifies the min block number, the max block number is set to the current block number + MAX_BLOCK_RANGE_BLOCKS; however, there is no check that the min block is less than the newly set max block number.

Bundles: Ensure that the min block number is inside the MAX_BLOCK_RANGE_BLOCKS

---

crates/op-rbuilder/src/builders/context.rs
crates/op-rbuilder/src/primitives/bundle.rs
crates/op-rbuilder/src/revert_protection.rs
crates/op-rbuilder/src/tests/framework/txs.rs
crates/op-rbuilder/src/tx.rs

Ref https://github.com/flashbots/op-rbuilder/pull/115#discussion_r2129931567

Fix bundle type reverting hashes optional param

---

crates/op-rbuilder/src/primitives/bundle.rs
crates/op-rbuilder/src/revert_protection.rs
crates/op-rbuilder/src/tests/vanilla/revert.rs

This PR:
- Moves the Bundle block number max/min validation out of the RPC hot path into the primitives folder and uses a custom error type to represent the validation error. It simplifies the RPC module.
- Adds unit tests for all the different conditions.
- Updates the integration test to account for the changes in #128.

Move bundle validation to primitives folder

---

crates/op-rbuilder/Cargo.toml
crates/op-rbuilder/src/bin/op-rbuilder/main.rs
crates/op-rbuilder/src/launcher.rs
crates/op-rbuilder/src/lib.rs

Before, in the src folder we had both a `main.rs` function and an import `lib.rs` one. This setup created problems because methods exported in lib were not available for main since I believe the execution contexts were different.
This PR changes that and splits the op-rbuilder in two components, a library (under `src`) and the op-rbuilder main binary (under `bin`) which consumes the library. Other than the main split in functionality this PR does not introduce any other ergonomics about how to structure better the library to be consumed by the main binary. I will leave that to followup PRs that consume this functionality.

Split op-rbuilder in lib and main

---

crates/op-rbuilder/src/builders/flashblocks/wspub.rs

Add pingpong and closing frame handle

---

crates/op-rbuilder/src/bin/tester/main.rs

The way we use the tester command to simulate the EL node, there is only a single logical endpoint. This was added as part of #132 to split the JSON-RPC calls since we use the same routine for testing where there is a more intentional split.

Fix regression on tester command

---

crates/op-rbuilder/src/tests/framework/apis.rs

Fixing a regression introduced in https://github.com/flashbots/op-rbuilder/pull/132 by which the output of the genesis command is not shown on terminal.

Genesis command outputs genesis file

---

crates/op-rbuilder/src/args/op.rs
crates/op-rbuilder/src/builders/flashblocks/config.rs
crates/op-rbuilder/src/builders/flashblocks/payload.rs
crates/op-rbuilder/src/builders/mod.rs
crates/op-rbuilder/src/metrics.rs
crates/op-rbuilder/src/tests/flashblocks/smoke.rs

Account for flashblocks time drift

---

crates/op-rbuilder/src/metrics.rs
crates/op-rbuilder/src/revert_protection.rs
crates/op-rbuilder/src/tx.rs

Add some telemetry for the `eth_sendBundle` endpoint. Specifically, introduce the following metrics:
* Number of total requests
* Reponse latency
And also log error messages instead of just returning the error to the caller.
Better monitoring/productionizing bundle support.
---

Add some telemetry for `eth_sendBundle`

---

README.md
crates/op-rbuilder/src/builders/flashblocks/service.rs
crates/op-rbuilder/src/builders/standard/payload.rs
crates/op-rbuilder/src/flashtestations/args.rs
crates/op-rbuilder/src/flashtestations/service.rs

Resolves #167 
Adds a separate cli flag for the TEE key to be funded.
---

Add cli flag for funding key

---

crates/op-rbuilder/src/builders/flashblocks/payload.rs

We have missing block when building deposit only blocks under high FCU pressure because we were pitting builder tx into first flashblock. 
---

Move builder tx right after deposits and put it into base flashblock

---

crates/op-rbuilder/src/builders/flashblocks/payload.rs

This change was in the way or the logic for targeting current block for inclusion
---

Remove without_updates for flashblocks

---

crates/op-rbuilder/src/tests/flashblocks.rs
crates/op-rbuilder/src/tests/framework/instance.rs

During testing we realized that the builder drivers are redundantly calculating a block on initialization.

Remove redundant account initialization

---

.github/workflows/release.yaml

Reverting format of release artifacts. Otherwise the artifact sync will not work correctly.
---

Revert op-rbuilder release workflow changes

---

.cargo/config.toml

Added some cargo flags to make builds reproducible
Needed so that people can manually verify the artifacts we publish when trying to bootstrap our TDX images from source

Add reproducibility flags

---

crates/op-rbuilder/src/builders/flashblocks/payload.rs

Record how many flashblocks we missed
We're not recording this metric properly at the moment
---

fix: record missing flashblocks

---

crates/op-rbuilder/src/builders/flashblocks/payload.rs

Change the location where we record the metrics for the number of txs in a block
This wasn't being recorded correctly for flashblocks
---

fix: record num txs built with flashblocks enabled

---

crates/op-rbuilder/src/builders/flashblocks/payload.rs
crates/op-rbuilder/src/builders/flashblocks/wspub.rs
crates/op-rbuilder/src/metrics.rs

Correct flashblock size metric

---

crates/op-rbuilder/src/args/mod.rs
crates/op-rbuilder/src/metrics.rs

#52 introduced build time environment variables for extra metrics, similar to what is done in reth.
Clap long version (--version) configuration was not overridden and was using by default the one used by eth.
This PR is a fix to this by using the correct envs.

fix: override clap long version envs

---

.github/workflows/op_rbuilder_checks.yaml
.github/workflows/op_rbuilder_release.yaml
.github/workflows/tdx_quote_provider_checks.yaml
.github/workflows/tdx_quote_provider_release.yaml

No-op changes mostly.  Renamed workflows, and fixed the release workflow for `op-rbuilder` to strip the `op-rbuilder/` prefix from the tag when deriving the version.
We want good unambiguous tags and meaningful version strings.

chore: update op-rbuilder ci for prefixed tagging

---

.github/workflows/op_rbuilder_release.yaml

Prepend `op-rbuilder/` (instead of `op-`) to `op-rbuilder'` release names

fix: release name

---

crates/op-rbuilder/src/args/op.rs
crates/op-rbuilder/src/builders/flashblocks/config.rs
crates/op-rbuilder/src/builders/flashblocks/payload.rs
crates/op-rbuilder/src/tests/flashblocks.rs

On Base Mainnet we don't calculate state root per flashblock, we control this with a flag. It only calculates state root when doing historical sync as it's necessary.  
For calculate state root, it does via rollup-boost and op-geth. https://github.com/flashbots/rollup-boost/pull/381
---

flag to determine if calculating state root

---

crates/op-rbuilder/src/builders/context.rs

We should check in this order to account for situations where searchers send lots of txs that are expensive to compute, but always revert since this is free for them to do with revert protection.
---

fix: check per-address gas limit before checking if the tx reverted

---

Cargo.lock
README.md
crates/op-rbuilder/Cargo.toml
crates/op-rbuilder/src/args/mod.rs

Close #232
Overwrite current `<CACHE_DIR>/reth/logs` directory for log files to `<CACHE_DIR>/op-rbuilder/logs` directory.
Still configurable with `--log.file.directory` arg.
Using reth's `Cli`, we already inherit different tracing layers for logging. 
The default value for the file logger point to `<CACHE_DIR>/reth/logs`.
If running op-rbuilder with reth, this can mix cache files.
This PR correctly set the file log output. You can access by default debug level trace and access log at:
- `~/.cache/op-rbuilder/logs` on Linux
- `~/Library/Caches/op-rbuilder/logs` on macOS
- `%localAppData%/op-rbuilder/logs` on Windows
Additional file logging configuration (accessible with `--help`):
```
--log.file.format <FORMAT>
The format to use for logs written to the log file
[default: terminal]
Possible …
```

feat: overwrite reth default cache directory

---

.github/workflows/tdx_quote_provider_release.yaml

Upload build artifacts of `tdx-quote-provider` w/o altering their names.

fix: dont mangle artifact binary name

---

.github/workflows/op_rbuilder_release.yaml

we build container images for 2 platforms and push them with the same tag, one over another.
this PR fixes that, and pushed an index image for both instead.

fix: push multi-platform container images
